logging:
  version: 1
  formatters:
    console:
      format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      formatter: console
  loggers:
    crawler:
      level: INFO
      handlers: [console]
    storage:
      level: INFO
      handlers: [console]